# fakepay Makefile

CAPABILITY_ID = "wasmcloud:example:fakepay"
NAME = "fakepay"
VENDOR = "Acme"
PROJECT = fakepay
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

