[package]
name = "hello_marco_usage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello_marco = { path = "../hello_marco" }
hello_marco_derive = { path = "../hello_marco/hello_marco_derive" }

